// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/LFDT-Panurus/panurus/token/services/storage/db/common"
	"github.com/LFDT-Panurus/panurus/token/services/storage/services/checks"
)

type Checker struct {
	CheckStub        func(context.Context) ([]common.Finding, error)
	checkMutex       sync.RWMutex
	checkArgsForCall []struct {
		arg1 context.Context
	}
	checkReturns struct {
		result1 []common.Finding
		result2 error
	}
	checkReturnsOnCall map[int]struct {
		result1 []common.Finding
		result2 error
	}
	ResolvableCheckersStub        func() []string
	resolvableCheckersMutex       sync.RWMutex
	resolvableCheckersArgsForCall []struct {
	}
	resolvableCheckersReturns struct {
		result1 []string
	}
	resolvableCheckersReturnsOnCall map[int]struct {
		result1 []string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Checker) Check(arg1 context.Context) ([]common.Finding, error) {
	fake.checkMutex.Lock()
	ret, specificReturn := fake.checkReturnsOnCall[len(fake.checkArgsForCall)]
	fake.checkArgsForCall = append(fake.checkArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CheckStub
	fakeReturns := fake.checkReturns
	fake.recordInvocation("Check", []interface{}{arg1})
	fake.checkMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Checker) CheckCallCount() int {
	fake.checkMutex.RLock()
	defer fake.checkMutex.RUnlock()
	return len(fake.checkArgsForCall)
}

func (fake *Checker) CheckCalls(stub func(context.Context) ([]common.Finding, error)) {
	fake.checkMutex.Lock()
	defer fake.checkMutex.Unlock()
	fake.CheckStub = stub
}

func (fake *Checker) CheckArgsForCall(i int) context.Context {
	fake.checkMutex.RLock()
	defer fake.checkMutex.RUnlock()
	argsForCall := fake.checkArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Checker) CheckReturns(result1 []common.Finding, result2 error) {
	fake.checkMutex.Lock()
	defer fake.checkMutex.Unlock()
	fake.CheckStub = nil
	fake.checkReturns = struct {
		result1 []common.Finding
		result2 error
	}{result1, result2}
}

func (fake *Checker) CheckReturnsOnCall(i int, result1 []common.Finding, result2 error) {
	fake.checkMutex.Lock()
	defer fake.checkMutex.Unlock()
	fake.CheckStub = nil
	if fake.checkReturnsOnCall == nil {
		fake.checkReturnsOnCall = make(map[int]struct {
			result1 []common.Finding
			result2 error
		})
	}
	fake.checkReturnsOnCall[i] = struct {
		result1 []common.Finding
		result2 error
	}{result1, result2}
}

func (fake *Checker) ResolvableCheckers() []string {
	fake.resolvableCheckersMutex.Lock()
	ret, specificReturn := fake.resolvableCheckersReturnsOnCall[len(fake.resolvableCheckersArgsForCall)]
	fake.resolvableCheckersArgsForCall = append(fake.resolvableCheckersArgsForCall, struct {
	}{})
	stub := fake.ResolvableCheckersStub
	fakeReturns := fake.resolvableCheckersReturns
	fake.recordInvocation("ResolvableCheckers", []interface{}{})
	fake.resolvableCheckersMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Checker) ResolvableCheckersCallCount() int {
	fake.resolvableCheckersMutex.RLock()
	defer fake.resolvableCheckersMutex.RUnlock()
	return len(fake.resolvableCheckersArgsForCall)
}

func (fake *Checker) ResolvableCheckersCalls(stub func() []string) {
	fake.resolvableCheckersMutex.Lock()
	defer fake.resolvableCheckersMutex.Unlock()
	fake.ResolvableCheckersStub = stub
}

func (fake *Checker) ResolvableCheckersReturns(result1 []string) {
	fake.resolvableCheckersMutex.Lock()
	defer fake.resolvableCheckersMutex.Unlock()
	fake.ResolvableCheckersStub = nil
	fake.resolvableCheckersReturns = struct {
		result1 []string
	}{result1}
}

func (fake *Checker) ResolvableCheckersReturnsOnCall(i int, result1 []string) {
	fake.resolvableCheckersMutex.Lock()
	defer fake.resolvableCheckersMutex.Unlock()
	fake.ResolvableCheckersStub = nil
	if fake.resolvableCheckersReturnsOnCall == nil {
		fake.resolvableCheckersReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.resolvableCheckersReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *Checker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Checker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ checks.Checker = new(Checker)
