// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"
	"time"

	"github.com/LFDT-Panurus/panurus/token/services/storage/db/driver"
	"github.com/LFDT-Panurus/panurus/token/services/storage/services/checks"
)

type Storage struct {
	AcquireLeadershipStub        func(context.Context, int64) (checks.Leadership, bool, error)
	acquireLeadershipMutex       sync.RWMutex
	acquireLeadershipArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	acquireLeadershipReturns struct {
		result1 checks.Leadership
		result2 bool
		result3 error
	}
	acquireLeadershipReturnsOnCall map[int]struct {
		result1 checks.Leadership
		result2 bool
		result3 error
	}
	ResolveFindingsNotSeenSinceStub        func(context.Context, []string, time.Time) (int64, error)
	resolveFindingsNotSeenSinceMutex       sync.RWMutex
	resolveFindingsNotSeenSinceArgsForCall []struct {
		arg1 context.Context
		arg2 []string
		arg3 time.Time
	}
	resolveFindingsNotSeenSinceReturns struct {
		result1 int64
		result2 error
	}
	resolveFindingsNotSeenSinceReturnsOnCall map[int]struct {
		result1 int64
		result2 error
	}
	UpsertFindingsStub        func(context.Context, []driver.FindingRecord, time.Time) error
	upsertFindingsMutex       sync.RWMutex
	upsertFindingsArgsForCall []struct {
		arg1 context.Context
		arg2 []driver.FindingRecord
		arg3 time.Time
	}
	upsertFindingsReturns struct {
		result1 error
	}
	upsertFindingsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Storage) AcquireLeadership(arg1 context.Context, arg2 int64) (checks.Leadership, bool, error) {
	fake.acquireLeadershipMutex.Lock()
	ret, specificReturn := fake.acquireLeadershipReturnsOnCall[len(fake.acquireLeadershipArgsForCall)]
	fake.acquireLeadershipArgsForCall = append(fake.acquireLeadershipArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.AcquireLeadershipStub
	fakeReturns := fake.acquireLeadershipReturns
	fake.recordInvocation("AcquireLeadership", []interface{}{arg1, arg2})
	fake.acquireLeadershipMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *Storage) AcquireLeadershipCallCount() int {
	fake.acquireLeadershipMutex.RLock()
	defer fake.acquireLeadershipMutex.RUnlock()
	return len(fake.acquireLeadershipArgsForCall)
}

func (fake *Storage) AcquireLeadershipCalls(stub func(context.Context, int64) (checks.Leadership, bool, error)) {
	fake.acquireLeadershipMutex.Lock()
	defer fake.acquireLeadershipMutex.Unlock()
	fake.AcquireLeadershipStub = stub
}

func (fake *Storage) AcquireLeadershipArgsForCall(i int) (context.Context, int64) {
	fake.acquireLeadershipMutex.RLock()
	defer fake.acquireLeadershipMutex.RUnlock()
	argsForCall := fake.acquireLeadershipArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) AcquireLeadershipReturns(result1 checks.Leadership, result2 bool, result3 error) {
	fake.acquireLeadershipMutex.Lock()
	defer fake.acquireLeadershipMutex.Unlock()
	fake.AcquireLeadershipStub = nil
	fake.acquireLeadershipReturns = struct {
		result1 checks.Leadership
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *Storage) AcquireLeadershipReturnsOnCall(i int, result1 checks.Leadership, result2 bool, result3 error) {
	fake.acquireLeadershipMutex.Lock()
	defer fake.acquireLeadershipMutex.Unlock()
	fake.AcquireLeadershipStub = nil
	if fake.acquireLeadershipReturnsOnCall == nil {
		fake.acquireLeadershipReturnsOnCall = make(map[int]struct {
			result1 checks.Leadership
			result2 bool
			result3 error
		})
	}
	fake.acquireLeadershipReturnsOnCall[i] = struct {
		result1 checks.Leadership
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *Storage) ResolveFindingsNotSeenSince(arg1 context.Context, arg2 []string, arg3 time.Time) (int64, error) {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.resolveFindingsNotSeenSinceMutex.Lock()
	ret, specificReturn := fake.resolveFindingsNotSeenSinceReturnsOnCall[len(fake.resolveFindingsNotSeenSinceArgsForCall)]
	fake.resolveFindingsNotSeenSinceArgsForCall = append(fake.resolveFindingsNotSeenSinceArgsForCall, struct {
		arg1 context.Context
		arg2 []string
		arg3 time.Time
	}{arg1, arg2Copy, arg3})
	stub := fake.ResolveFindingsNotSeenSinceStub
	fakeReturns := fake.resolveFindingsNotSeenSinceReturns
	fake.recordInvocation("ResolveFindingsNotSeenSince", []interface{}{arg1, arg2Copy, arg3})
	fake.resolveFindingsNotSeenSinceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ResolveFindingsNotSeenSinceCallCount() int {
	fake.resolveFindingsNotSeenSinceMutex.RLock()
	defer fake.resolveFindingsNotSeenSinceMutex.RUnlock()
	return len(fake.resolveFindingsNotSeenSinceArgsForCall)
}

func (fake *Storage) ResolveFindingsNotSeenSinceCalls(stub func(context.Context, []string, time.Time) (int64, error)) {
	fake.resolveFindingsNotSeenSinceMutex.Lock()
	defer fake.resolveFindingsNotSeenSinceMutex.Unlock()
	fake.ResolveFindingsNotSeenSinceStub = stub
}

func (fake *Storage) ResolveFindingsNotSeenSinceArgsForCall(i int) (context.Context, []string, time.Time) {
	fake.resolveFindingsNotSeenSinceMutex.RLock()
	defer fake.resolveFindingsNotSeenSinceMutex.RUnlock()
	argsForCall := fake.resolveFindingsNotSeenSinceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) ResolveFindingsNotSeenSinceReturns(result1 int64, result2 error) {
	fake.resolveFindingsNotSeenSinceMutex.Lock()
	defer fake.resolveFindingsNotSeenSinceMutex.Unlock()
	fake.ResolveFindingsNotSeenSinceStub = nil
	fake.resolveFindingsNotSeenSinceReturns = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *Storage) ResolveFindingsNotSeenSinceReturnsOnCall(i int, result1 int64, result2 error) {
	fake.resolveFindingsNotSeenSinceMutex.Lock()
	defer fake.resolveFindingsNotSeenSinceMutex.Unlock()
	fake.ResolveFindingsNotSeenSinceStub = nil
	if fake.resolveFindingsNotSeenSinceReturnsOnCall == nil {
		fake.resolveFindingsNotSeenSinceReturnsOnCall = make(map[int]struct {
			result1 int64
			result2 error
		})
	}
	fake.resolveFindingsNotSeenSinceReturnsOnCall[i] = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *Storage) UpsertFindings(arg1 context.Context, arg2 []driver.FindingRecord, arg3 time.Time) error {
	var arg2Copy []driver.FindingRecord
	if arg2 != nil {
		arg2Copy = make([]driver.FindingRecord, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.upsertFindingsMutex.Lock()
	ret, specificReturn := fake.upsertFindingsReturnsOnCall[len(fake.upsertFindingsArgsForCall)]
	fake.upsertFindingsArgsForCall = append(fake.upsertFindingsArgsForCall, struct {
		arg1 context.Context
		arg2 []driver.FindingRecord
		arg3 time.Time
	}{arg1, arg2Copy, arg3})
	stub := fake.UpsertFindingsStub
	fakeReturns := fake.upsertFindingsReturns
	fake.recordInvocation("UpsertFindings", []interface{}{arg1, arg2Copy, arg3})
	fake.upsertFindingsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) UpsertFindingsCallCount() int {
	fake.upsertFindingsMutex.RLock()
	defer fake.upsertFindingsMutex.RUnlock()
	return len(fake.upsertFindingsArgsForCall)
}

func (fake *Storage) UpsertFindingsCalls(stub func(context.Context, []driver.FindingRecord, time.Time) error) {
	fake.upsertFindingsMutex.Lock()
	defer fake.upsertFindingsMutex.Unlock()
	fake.UpsertFindingsStub = stub
}

func (fake *Storage) UpsertFindingsArgsForCall(i int) (context.Context, []driver.FindingRecord, time.Time) {
	fake.upsertFindingsMutex.RLock()
	defer fake.upsertFindingsMutex.RUnlock()
	argsForCall := fake.upsertFindingsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) UpsertFindingsReturns(result1 error) {
	fake.upsertFindingsMutex.Lock()
	defer fake.upsertFindingsMutex.Unlock()
	fake.UpsertFindingsStub = nil
	fake.upsertFindingsReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) UpsertFindingsReturnsOnCall(i int, result1 error) {
	fake.upsertFindingsMutex.Lock()
	defer fake.upsertFindingsMutex.Unlock()
	fake.UpsertFindingsStub = nil
	if fake.upsertFindingsReturnsOnCall == nil {
		fake.upsertFindingsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.upsertFindingsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Storage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ checks.Storage = new(Storage)
