// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/LFDT-Panurus/panurus/token"
	"github.com/LFDT-Panurus/panurus/token/services/network/fabric/endorsement/fsc"
	"github.com/hyperledger-labs/fabric-smart-client/platform/view/view"
)

type EndorserSelector struct {
	SelectEndorsersStub        func(context.Context, token.TMSID, []view.Identity) ([]view.Identity, error)
	selectEndorsersMutex       sync.RWMutex
	selectEndorsersArgsForCall []struct {
		arg1 context.Context
		arg2 token.TMSID
		arg3 []view.Identity
	}
	selectEndorsersReturns struct {
		result1 []view.Identity
		result2 error
	}
	selectEndorsersReturnsOnCall map[int]struct {
		result1 []view.Identity
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *EndorserSelector) SelectEndorsers(arg1 context.Context, arg2 token.TMSID, arg3 []view.Identity) ([]view.Identity, error) {
	var arg3Copy []view.Identity
	if arg3 != nil {
		arg3Copy = make([]view.Identity, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.selectEndorsersMutex.Lock()
	ret, specificReturn := fake.selectEndorsersReturnsOnCall[len(fake.selectEndorsersArgsForCall)]
	fake.selectEndorsersArgsForCall = append(fake.selectEndorsersArgsForCall, struct {
		arg1 context.Context
		arg2 token.TMSID
		arg3 []view.Identity
	}{arg1, arg2, arg3Copy})
	stub := fake.SelectEndorsersStub
	fakeReturns := fake.selectEndorsersReturns
	fake.recordInvocation("SelectEndorsers", []interface{}{arg1, arg2, arg3Copy})
	fake.selectEndorsersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EndorserSelector) SelectEndorsersCallCount() int {
	fake.selectEndorsersMutex.RLock()
	defer fake.selectEndorsersMutex.RUnlock()
	return len(fake.selectEndorsersArgsForCall)
}

func (fake *EndorserSelector) SelectEndorsersCalls(stub func(context.Context, token.TMSID, []view.Identity) ([]view.Identity, error)) {
	fake.selectEndorsersMutex.Lock()
	defer fake.selectEndorsersMutex.Unlock()
	fake.SelectEndorsersStub = stub
}

func (fake *EndorserSelector) SelectEndorsersArgsForCall(i int) (context.Context, token.TMSID, []view.Identity) {
	fake.selectEndorsersMutex.RLock()
	defer fake.selectEndorsersMutex.RUnlock()
	argsForCall := fake.selectEndorsersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *EndorserSelector) SelectEndorsersReturns(result1 []view.Identity, result2 error) {
	fake.selectEndorsersMutex.Lock()
	defer fake.selectEndorsersMutex.Unlock()
	fake.SelectEndorsersStub = nil
	fake.selectEndorsersReturns = struct {
		result1 []view.Identity
		result2 error
	}{result1, result2}
}

func (fake *EndorserSelector) SelectEndorsersReturnsOnCall(i int, result1 []view.Identity, result2 error) {
	fake.selectEndorsersMutex.Lock()
	defer fake.selectEndorsersMutex.Unlock()
	fake.SelectEndorsersStub = nil
	if fake.selectEndorsersReturnsOnCall == nil {
		fake.selectEndorsersReturnsOnCall = make(map[int]struct {
			result1 []view.Identity
			result2 error
		})
	}
	fake.selectEndorsersReturnsOnCall[i] = struct {
		result1 []view.Identity
		result2 error
	}{result1, result2}
}

func (fake *EndorserSelector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *EndorserSelector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fsc.EndorserSelector = new(EndorserSelector)
