// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/LFDT-Panurus/panurus/token/services/network/fabric/endorsement/fsc"
	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/driver"
	"github.com/hyperledger-labs/fabric-smart-client/platform/view/view"
)

type MSPManager struct {
	GetMSPIdentifierStub        func([]byte) (string, error)
	getMSPIdentifierMutex       sync.RWMutex
	getMSPIdentifierArgsForCall []struct {
		arg1 []byte
	}
	getMSPIdentifierReturns struct {
		result1 string
		result2 error
	}
	getMSPIdentifierReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetVerifierStub        func(view.Identity) (driver.Verifier, error)
	getVerifierMutex       sync.RWMutex
	getVerifierArgsForCall []struct {
		arg1 view.Identity
	}
	getVerifierReturns struct {
		result1 driver.Verifier
		result2 error
	}
	getVerifierReturnsOnCall map[int]struct {
		result1 driver.Verifier
		result2 error
	}
	IsValidStub        func(view.Identity) error
	isValidMutex       sync.RWMutex
	isValidArgsForCall []struct {
		arg1 view.Identity
	}
	isValidReturns struct {
		result1 error
	}
	isValidReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *MSPManager) GetMSPIdentifier(arg1 []byte) (string, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.getMSPIdentifierMutex.Lock()
	ret, specificReturn := fake.getMSPIdentifierReturnsOnCall[len(fake.getMSPIdentifierArgsForCall)]
	fake.getMSPIdentifierArgsForCall = append(fake.getMSPIdentifierArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.GetMSPIdentifierStub
	fakeReturns := fake.getMSPIdentifierReturns
	fake.recordInvocation("GetMSPIdentifier", []interface{}{arg1Copy})
	fake.getMSPIdentifierMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MSPManager) GetMSPIdentifierCallCount() int {
	fake.getMSPIdentifierMutex.RLock()
	defer fake.getMSPIdentifierMutex.RUnlock()
	return len(fake.getMSPIdentifierArgsForCall)
}

func (fake *MSPManager) GetMSPIdentifierCalls(stub func([]byte) (string, error)) {
	fake.getMSPIdentifierMutex.Lock()
	defer fake.getMSPIdentifierMutex.Unlock()
	fake.GetMSPIdentifierStub = stub
}

func (fake *MSPManager) GetMSPIdentifierArgsForCall(i int) []byte {
	fake.getMSPIdentifierMutex.RLock()
	defer fake.getMSPIdentifierMutex.RUnlock()
	argsForCall := fake.getMSPIdentifierArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MSPManager) GetMSPIdentifierReturns(result1 string, result2 error) {
	fake.getMSPIdentifierMutex.Lock()
	defer fake.getMSPIdentifierMutex.Unlock()
	fake.GetMSPIdentifierStub = nil
	fake.getMSPIdentifierReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *MSPManager) GetMSPIdentifierReturnsOnCall(i int, result1 string, result2 error) {
	fake.getMSPIdentifierMutex.Lock()
	defer fake.getMSPIdentifierMutex.Unlock()
	fake.GetMSPIdentifierStub = nil
	if fake.getMSPIdentifierReturnsOnCall == nil {
		fake.getMSPIdentifierReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getMSPIdentifierReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *MSPManager) GetVerifier(arg1 view.Identity) (driver.Verifier, error) {
	fake.getVerifierMutex.Lock()
	ret, specificReturn := fake.getVerifierReturnsOnCall[len(fake.getVerifierArgsForCall)]
	fake.getVerifierArgsForCall = append(fake.getVerifierArgsForCall, struct {
		arg1 view.Identity
	}{arg1})
	stub := fake.GetVerifierStub
	fakeReturns := fake.getVerifierReturns
	fake.recordInvocation("GetVerifier", []interface{}{arg1})
	fake.getVerifierMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MSPManager) GetVerifierCallCount() int {
	fake.getVerifierMutex.RLock()
	defer fake.getVerifierMutex.RUnlock()
	return len(fake.getVerifierArgsForCall)
}

func (fake *MSPManager) GetVerifierCalls(stub func(view.Identity) (driver.Verifier, error)) {
	fake.getVerifierMutex.Lock()
	defer fake.getVerifierMutex.Unlock()
	fake.GetVerifierStub = stub
}

func (fake *MSPManager) GetVerifierArgsForCall(i int) view.Identity {
	fake.getVerifierMutex.RLock()
	defer fake.getVerifierMutex.RUnlock()
	argsForCall := fake.getVerifierArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MSPManager) GetVerifierReturns(result1 driver.Verifier, result2 error) {
	fake.getVerifierMutex.Lock()
	defer fake.getVerifierMutex.Unlock()
	fake.GetVerifierStub = nil
	fake.getVerifierReturns = struct {
		result1 driver.Verifier
		result2 error
	}{result1, result2}
}

func (fake *MSPManager) GetVerifierReturnsOnCall(i int, result1 driver.Verifier, result2 error) {
	fake.getVerifierMutex.Lock()
	defer fake.getVerifierMutex.Unlock()
	fake.GetVerifierStub = nil
	if fake.getVerifierReturnsOnCall == nil {
		fake.getVerifierReturnsOnCall = make(map[int]struct {
			result1 driver.Verifier
			result2 error
		})
	}
	fake.getVerifierReturnsOnCall[i] = struct {
		result1 driver.Verifier
		result2 error
	}{result1, result2}
}

func (fake *MSPManager) IsValid(arg1 view.Identity) error {
	fake.isValidMutex.Lock()
	ret, specificReturn := fake.isValidReturnsOnCall[len(fake.isValidArgsForCall)]
	fake.isValidArgsForCall = append(fake.isValidArgsForCall, struct {
		arg1 view.Identity
	}{arg1})
	stub := fake.IsValidStub
	fakeReturns := fake.isValidReturns
	fake.recordInvocation("IsValid", []interface{}{arg1})
	fake.isValidMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MSPManager) IsValidCallCount() int {
	fake.isValidMutex.RLock()
	defer fake.isValidMutex.RUnlock()
	return len(fake.isValidArgsForCall)
}

func (fake *MSPManager) IsValidCalls(stub func(view.Identity) error) {
	fake.isValidMutex.Lock()
	defer fake.isValidMutex.Unlock()
	fake.IsValidStub = stub
}

func (fake *MSPManager) IsValidArgsForCall(i int) view.Identity {
	fake.isValidMutex.RLock()
	defer fake.isValidMutex.RUnlock()
	argsForCall := fake.isValidArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MSPManager) IsValidReturns(result1 error) {
	fake.isValidMutex.Lock()
	defer fake.isValidMutex.Unlock()
	fake.IsValidStub = nil
	fake.isValidReturns = struct {
		result1 error
	}{result1}
}

func (fake *MSPManager) IsValidReturnsOnCall(i int, result1 error) {
	fake.isValidMutex.Lock()
	defer fake.isValidMutex.Unlock()
	fake.IsValidStub = nil
	if fake.isValidReturnsOnCall == nil {
		fake.isValidReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.isValidReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MSPManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *MSPManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fsc.MSPManager = new(MSPManager)
