// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/LFDT-Panurus/panurus/token/driver"
	"github.com/LFDT-Panurus/panurus/token/services/network/fabric/endorsement/fsc"
)

type PublicParamsValidator struct {
	PublicParametersFromBytesStub        func([]byte) (driver.PublicParameters, error)
	publicParametersFromBytesMutex       sync.RWMutex
	publicParametersFromBytesArgsForCall []struct {
		arg1 []byte
	}
	publicParametersFromBytesReturns struct {
		result1 driver.PublicParameters
		result2 error
	}
	publicParametersFromBytesReturnsOnCall map[int]struct {
		result1 driver.PublicParameters
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PublicParamsValidator) PublicParametersFromBytes(arg1 []byte) (driver.PublicParameters, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.publicParametersFromBytesMutex.Lock()
	ret, specificReturn := fake.publicParametersFromBytesReturnsOnCall[len(fake.publicParametersFromBytesArgsForCall)]
	fake.publicParametersFromBytesArgsForCall = append(fake.publicParametersFromBytesArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.PublicParametersFromBytesStub
	fakeReturns := fake.publicParametersFromBytesReturns
	fake.recordInvocation("PublicParametersFromBytes", []interface{}{arg1Copy})
	fake.publicParametersFromBytesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PublicParamsValidator) PublicParametersFromBytesCallCount() int {
	fake.publicParametersFromBytesMutex.RLock()
	defer fake.publicParametersFromBytesMutex.RUnlock()
	return len(fake.publicParametersFromBytesArgsForCall)
}

func (fake *PublicParamsValidator) PublicParametersFromBytesCalls(stub func([]byte) (driver.PublicParameters, error)) {
	fake.publicParametersFromBytesMutex.Lock()
	defer fake.publicParametersFromBytesMutex.Unlock()
	fake.PublicParametersFromBytesStub = stub
}

func (fake *PublicParamsValidator) PublicParametersFromBytesArgsForCall(i int) []byte {
	fake.publicParametersFromBytesMutex.RLock()
	defer fake.publicParametersFromBytesMutex.RUnlock()
	argsForCall := fake.publicParametersFromBytesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PublicParamsValidator) PublicParametersFromBytesReturns(result1 driver.PublicParameters, result2 error) {
	fake.publicParametersFromBytesMutex.Lock()
	defer fake.publicParametersFromBytesMutex.Unlock()
	fake.PublicParametersFromBytesStub = nil
	fake.publicParametersFromBytesReturns = struct {
		result1 driver.PublicParameters
		result2 error
	}{result1, result2}
}

func (fake *PublicParamsValidator) PublicParametersFromBytesReturnsOnCall(i int, result1 driver.PublicParameters, result2 error) {
	fake.publicParametersFromBytesMutex.Lock()
	defer fake.publicParametersFromBytesMutex.Unlock()
	fake.PublicParametersFromBytesStub = nil
	if fake.publicParametersFromBytesReturnsOnCall == nil {
		fake.publicParametersFromBytesReturnsOnCall = make(map[int]struct {
			result1 driver.PublicParameters
			result2 error
		})
	}
	fake.publicParametersFromBytesReturnsOnCall[i] = struct {
		result1 driver.PublicParameters
		result2 error
	}{result1, result2}
}

func (fake *PublicParamsValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PublicParamsValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fsc.PublicParamsValidator = new(PublicParamsValidator)
