// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/LFDT-Panurus/panurus/token"
)

type SelectorManagerProvider struct {
	SelectorManagerStub        func() (token.SelectorManager, error)
	selectorManagerMutex       sync.RWMutex
	selectorManagerArgsForCall []struct {
	}
	selectorManagerReturns struct {
		result1 token.SelectorManager
		result2 error
	}
	selectorManagerReturnsOnCall map[int]struct {
		result1 token.SelectorManager
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *SelectorManagerProvider) SelectorManager() (token.SelectorManager, error) {
	fake.selectorManagerMutex.Lock()
	ret, specificReturn := fake.selectorManagerReturnsOnCall[len(fake.selectorManagerArgsForCall)]
	fake.selectorManagerArgsForCall = append(fake.selectorManagerArgsForCall, struct {
	}{})
	stub := fake.SelectorManagerStub
	fakeReturns := fake.selectorManagerReturns
	fake.recordInvocation("SelectorManager", []interface{}{})
	fake.selectorManagerMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *SelectorManagerProvider) SelectorManagerCallCount() int {
	fake.selectorManagerMutex.RLock()
	defer fake.selectorManagerMutex.RUnlock()
	return len(fake.selectorManagerArgsForCall)
}

func (fake *SelectorManagerProvider) SelectorManagerCalls(stub func() (token.SelectorManager, error)) {
	fake.selectorManagerMutex.Lock()
	defer fake.selectorManagerMutex.Unlock()
	fake.SelectorManagerStub = stub
}

func (fake *SelectorManagerProvider) SelectorManagerReturns(result1 token.SelectorManager, result2 error) {
	fake.selectorManagerMutex.Lock()
	defer fake.selectorManagerMutex.Unlock()
	fake.SelectorManagerStub = nil
	fake.selectorManagerReturns = struct {
		result1 token.SelectorManager
		result2 error
	}{result1, result2}
}

func (fake *SelectorManagerProvider) SelectorManagerReturnsOnCall(i int, result1 token.SelectorManager, result2 error) {
	fake.selectorManagerMutex.Lock()
	defer fake.selectorManagerMutex.Unlock()
	fake.SelectorManagerStub = nil
	if fake.selectorManagerReturnsOnCall == nil {
		fake.selectorManagerReturnsOnCall = make(map[int]struct {
			result1 token.SelectorManager
			result2 error
		})
	}
	fake.selectorManagerReturnsOnCall[i] = struct {
		result1 token.SelectorManager
		result2 error
	}{result1, result2}
}

func (fake *SelectorManagerProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *SelectorManagerProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
