// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/LFDT-Panurus/panurus/token/services/selector/sherdlock"
	"github.com/LFDT-Panurus/panurus/token/services/utils/types/transaction"
	"github.com/LFDT-Panurus/panurus/token/token"
)

type FakeBatchLocker struct {
	LockBatchStub        func(context.Context, []*token.ID, transaction.ID, string) ([]*token.ID, error)
	lockBatchMutex       sync.RWMutex
	lockBatchArgsForCall []struct {
		arg1 context.Context
		arg2 []*token.ID
		arg3 transaction.ID
		arg4 string
	}
	lockBatchReturns struct {
		result1 []*token.ID
		result2 error
	}
	lockBatchReturnsOnCall map[int]struct {
		result1 []*token.ID
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatchLocker) LockBatch(arg1 context.Context, arg2 []*token.ID, arg3 transaction.ID, arg4 string) ([]*token.ID, error) {
	var arg2Copy []*token.ID
	if arg2 != nil {
		arg2Copy = make([]*token.ID, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.lockBatchMutex.Lock()
	ret, specificReturn := fake.lockBatchReturnsOnCall[len(fake.lockBatchArgsForCall)]
	fake.lockBatchArgsForCall = append(fake.lockBatchArgsForCall, struct {
		arg1 context.Context
		arg2 []*token.ID
		arg3 transaction.ID
		arg4 string
	}{arg1, arg2Copy, arg3, arg4})
	stub := fake.LockBatchStub
	fakeReturns := fake.lockBatchReturns
	fake.recordInvocation("LockBatch", []interface{}{arg1, arg2Copy, arg3, arg4})
	fake.lockBatchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBatchLocker) LockBatchCallCount() int {
	fake.lockBatchMutex.RLock()
	defer fake.lockBatchMutex.RUnlock()
	return len(fake.lockBatchArgsForCall)
}

func (fake *FakeBatchLocker) LockBatchCalls(stub func(context.Context, []*token.ID, transaction.ID, string) ([]*token.ID, error)) {
	fake.lockBatchMutex.Lock()
	defer fake.lockBatchMutex.Unlock()
	fake.LockBatchStub = stub
}

func (fake *FakeBatchLocker) LockBatchArgsForCall(i int) (context.Context, []*token.ID, transaction.ID, string) {
	fake.lockBatchMutex.RLock()
	defer fake.lockBatchMutex.RUnlock()
	argsForCall := fake.lockBatchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeBatchLocker) LockBatchReturns(result1 []*token.ID, result2 error) {
	fake.lockBatchMutex.Lock()
	defer fake.lockBatchMutex.Unlock()
	fake.LockBatchStub = nil
	fake.lockBatchReturns = struct {
		result1 []*token.ID
		result2 error
	}{result1, result2}
}

func (fake *FakeBatchLocker) LockBatchReturnsOnCall(i int, result1 []*token.ID, result2 error) {
	fake.lockBatchMutex.Lock()
	defer fake.lockBatchMutex.Unlock()
	fake.LockBatchStub = nil
	if fake.lockBatchReturnsOnCall == nil {
		fake.lockBatchReturnsOnCall = make(map[int]struct {
			result1 []*token.ID
			result2 error
		})
	}
	fake.lockBatchReturnsOnCall[i] = struct {
		result1 []*token.ID
		result2 error
	}{result1, result2}
}

func (fake *FakeBatchLocker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatchLocker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sherdlock.BatchLocker = new(FakeBatchLocker)
