// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/LFDT-Panurus/panurus/token/driver"
	"github.com/LFDT-Panurus/panurus/token/services/selector/sherdlock"
	"github.com/LFDT-Panurus/panurus/token/token"
)

type FakeTokenDB struct {
	HasAnySpendableTokensStub        func(context.Context, string, token.Type) (bool, error)
	hasAnySpendableTokensMutex       sync.RWMutex
	hasAnySpendableTokensArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 token.Type
	}
	hasAnySpendableTokensReturns struct {
		result1 bool
		result2 error
	}
	hasAnySpendableTokensReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	SpendableTokensIteratorByStub        func(context.Context, string, token.Type) (driver.SpendableTokensIterator, error)
	spendableTokensIteratorByMutex       sync.RWMutex
	spendableTokensIteratorByArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 token.Type
	}
	spendableTokensIteratorByReturns struct {
		result1 driver.SpendableTokensIterator
		result2 error
	}
	spendableTokensIteratorByReturnsOnCall map[int]struct {
		result1 driver.SpendableTokensIterator
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTokenDB) HasAnySpendableTokens(arg1 context.Context, arg2 string, arg3 token.Type) (bool, error) {
	fake.hasAnySpendableTokensMutex.Lock()
	ret, specificReturn := fake.hasAnySpendableTokensReturnsOnCall[len(fake.hasAnySpendableTokensArgsForCall)]
	fake.hasAnySpendableTokensArgsForCall = append(fake.hasAnySpendableTokensArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 token.Type
	}{arg1, arg2, arg3})
	stub := fake.HasAnySpendableTokensStub
	fakeReturns := fake.hasAnySpendableTokensReturns
	fake.recordInvocation("HasAnySpendableTokens", []interface{}{arg1, arg2, arg3})
	fake.hasAnySpendableTokensMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTokenDB) HasAnySpendableTokensCallCount() int {
	fake.hasAnySpendableTokensMutex.RLock()
	defer fake.hasAnySpendableTokensMutex.RUnlock()
	return len(fake.hasAnySpendableTokensArgsForCall)
}

func (fake *FakeTokenDB) HasAnySpendableTokensCalls(stub func(context.Context, string, token.Type) (bool, error)) {
	fake.hasAnySpendableTokensMutex.Lock()
	defer fake.hasAnySpendableTokensMutex.Unlock()
	fake.HasAnySpendableTokensStub = stub
}

func (fake *FakeTokenDB) HasAnySpendableTokensArgsForCall(i int) (context.Context, string, token.Type) {
	fake.hasAnySpendableTokensMutex.RLock()
	defer fake.hasAnySpendableTokensMutex.RUnlock()
	argsForCall := fake.hasAnySpendableTokensArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTokenDB) HasAnySpendableTokensReturns(result1 bool, result2 error) {
	fake.hasAnySpendableTokensMutex.Lock()
	defer fake.hasAnySpendableTokensMutex.Unlock()
	fake.HasAnySpendableTokensStub = nil
	fake.hasAnySpendableTokensReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenDB) HasAnySpendableTokensReturnsOnCall(i int, result1 bool, result2 error) {
	fake.hasAnySpendableTokensMutex.Lock()
	defer fake.hasAnySpendableTokensMutex.Unlock()
	fake.HasAnySpendableTokensStub = nil
	if fake.hasAnySpendableTokensReturnsOnCall == nil {
		fake.hasAnySpendableTokensReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.hasAnySpendableTokensReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenDB) SpendableTokensIteratorBy(arg1 context.Context, arg2 string, arg3 token.Type) (driver.SpendableTokensIterator, error) {
	fake.spendableTokensIteratorByMutex.Lock()
	ret, specificReturn := fake.spendableTokensIteratorByReturnsOnCall[len(fake.spendableTokensIteratorByArgsForCall)]
	fake.spendableTokensIteratorByArgsForCall = append(fake.spendableTokensIteratorByArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 token.Type
	}{arg1, arg2, arg3})
	stub := fake.SpendableTokensIteratorByStub
	fakeReturns := fake.spendableTokensIteratorByReturns
	fake.recordInvocation("SpendableTokensIteratorBy", []interface{}{arg1, arg2, arg3})
	fake.spendableTokensIteratorByMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTokenDB) SpendableTokensIteratorByCallCount() int {
	fake.spendableTokensIteratorByMutex.RLock()
	defer fake.spendableTokensIteratorByMutex.RUnlock()
	return len(fake.spendableTokensIteratorByArgsForCall)
}

func (fake *FakeTokenDB) SpendableTokensIteratorByCalls(stub func(context.Context, string, token.Type) (driver.SpendableTokensIterator, error)) {
	fake.spendableTokensIteratorByMutex.Lock()
	defer fake.spendableTokensIteratorByMutex.Unlock()
	fake.SpendableTokensIteratorByStub = stub
}

func (fake *FakeTokenDB) SpendableTokensIteratorByArgsForCall(i int) (context.Context, string, token.Type) {
	fake.spendableTokensIteratorByMutex.RLock()
	defer fake.spendableTokensIteratorByMutex.RUnlock()
	argsForCall := fake.spendableTokensIteratorByArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTokenDB) SpendableTokensIteratorByReturns(result1 driver.SpendableTokensIterator, result2 error) {
	fake.spendableTokensIteratorByMutex.Lock()
	defer fake.spendableTokensIteratorByMutex.Unlock()
	fake.SpendableTokensIteratorByStub = nil
	fake.spendableTokensIteratorByReturns = struct {
		result1 driver.SpendableTokensIterator
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenDB) SpendableTokensIteratorByReturnsOnCall(i int, result1 driver.SpendableTokensIterator, result2 error) {
	fake.spendableTokensIteratorByMutex.Lock()
	defer fake.spendableTokensIteratorByMutex.Unlock()
	fake.SpendableTokensIteratorByStub = nil
	if fake.spendableTokensIteratorByReturnsOnCall == nil {
		fake.spendableTokensIteratorByReturnsOnCall = make(map[int]struct {
			result1 driver.SpendableTokensIterator
			result2 error
		})
	}
	fake.spendableTokensIteratorByReturnsOnCall[i] = struct {
		result1 driver.SpendableTokensIterator
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenDB) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTokenDB) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sherdlock.TokenDB = new(FakeTokenDB)
