// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"math/big"
	"sync"

	"github.com/LFDT-Panurus/panurus/token/services/selector/sherdlock"
	"github.com/LFDT-Panurus/panurus/token/token"
)

type FakeTokenFetcher struct {
	HasEnoughSpendableTokensStub        func(context.Context, string, token.Type, *big.Int) (bool, error)
	hasEnoughSpendableTokensMutex       sync.RWMutex
	hasEnoughSpendableTokensArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 token.Type
		arg4 *big.Int
	}
	hasEnoughSpendableTokensReturns struct {
		result1 bool
		result2 error
	}
	hasEnoughSpendableTokensReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	UnspentTokensIteratorByStub        func(context.Context, string, token.Type) (sherdlock.Iterator[*token.UnspentTokenInWallet], error)
	unspentTokensIteratorByMutex       sync.RWMutex
	unspentTokensIteratorByArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 token.Type
	}
	unspentTokensIteratorByReturns struct {
		result1 sherdlock.Iterator[*token.UnspentTokenInWallet]
		result2 error
	}
	unspentTokensIteratorByReturnsOnCall map[int]struct {
		result1 sherdlock.Iterator[*token.UnspentTokenInWallet]
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTokenFetcher) HasEnoughSpendableTokens(arg1 context.Context, arg2 string, arg3 token.Type, arg4 *big.Int) (bool, error) {
	fake.hasEnoughSpendableTokensMutex.Lock()
	ret, specificReturn := fake.hasEnoughSpendableTokensReturnsOnCall[len(fake.hasEnoughSpendableTokensArgsForCall)]
	fake.hasEnoughSpendableTokensArgsForCall = append(fake.hasEnoughSpendableTokensArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 token.Type
		arg4 *big.Int
	}{arg1, arg2, arg3, arg4})
	stub := fake.HasEnoughSpendableTokensStub
	fakeReturns := fake.hasEnoughSpendableTokensReturns
	fake.recordInvocation("HasEnoughSpendableTokens", []interface{}{arg1, arg2, arg3, arg4})
	fake.hasEnoughSpendableTokensMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTokenFetcher) HasEnoughSpendableTokensCallCount() int {
	fake.hasEnoughSpendableTokensMutex.RLock()
	defer fake.hasEnoughSpendableTokensMutex.RUnlock()
	return len(fake.hasEnoughSpendableTokensArgsForCall)
}

func (fake *FakeTokenFetcher) HasEnoughSpendableTokensCalls(stub func(context.Context, string, token.Type, *big.Int) (bool, error)) {
	fake.hasEnoughSpendableTokensMutex.Lock()
	defer fake.hasEnoughSpendableTokensMutex.Unlock()
	fake.HasEnoughSpendableTokensStub = stub
}

func (fake *FakeTokenFetcher) HasEnoughSpendableTokensArgsForCall(i int) (context.Context, string, token.Type, *big.Int) {
	fake.hasEnoughSpendableTokensMutex.RLock()
	defer fake.hasEnoughSpendableTokensMutex.RUnlock()
	argsForCall := fake.hasEnoughSpendableTokensArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeTokenFetcher) HasEnoughSpendableTokensReturns(result1 bool, result2 error) {
	fake.hasEnoughSpendableTokensMutex.Lock()
	defer fake.hasEnoughSpendableTokensMutex.Unlock()
	fake.HasEnoughSpendableTokensStub = nil
	fake.hasEnoughSpendableTokensReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenFetcher) HasEnoughSpendableTokensReturnsOnCall(i int, result1 bool, result2 error) {
	fake.hasEnoughSpendableTokensMutex.Lock()
	defer fake.hasEnoughSpendableTokensMutex.Unlock()
	fake.HasEnoughSpendableTokensStub = nil
	if fake.hasEnoughSpendableTokensReturnsOnCall == nil {
		fake.hasEnoughSpendableTokensReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.hasEnoughSpendableTokensReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenFetcher) UnspentTokensIteratorBy(arg1 context.Context, arg2 string, arg3 token.Type) (sherdlock.Iterator[*token.UnspentTokenInWallet], error) {
	fake.unspentTokensIteratorByMutex.Lock()
	ret, specificReturn := fake.unspentTokensIteratorByReturnsOnCall[len(fake.unspentTokensIteratorByArgsForCall)]
	fake.unspentTokensIteratorByArgsForCall = append(fake.unspentTokensIteratorByArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 token.Type
	}{arg1, arg2, arg3})
	stub := fake.UnspentTokensIteratorByStub
	fakeReturns := fake.unspentTokensIteratorByReturns
	fake.recordInvocation("UnspentTokensIteratorBy", []interface{}{arg1, arg2, arg3})
	fake.unspentTokensIteratorByMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTokenFetcher) UnspentTokensIteratorByCallCount() int {
	fake.unspentTokensIteratorByMutex.RLock()
	defer fake.unspentTokensIteratorByMutex.RUnlock()
	return len(fake.unspentTokensIteratorByArgsForCall)
}

func (fake *FakeTokenFetcher) UnspentTokensIteratorByCalls(stub func(context.Context, string, token.Type) (sherdlock.Iterator[*token.UnspentTokenInWallet], error)) {
	fake.unspentTokensIteratorByMutex.Lock()
	defer fake.unspentTokensIteratorByMutex.Unlock()
	fake.UnspentTokensIteratorByStub = stub
}

func (fake *FakeTokenFetcher) UnspentTokensIteratorByArgsForCall(i int) (context.Context, string, token.Type) {
	fake.unspentTokensIteratorByMutex.RLock()
	defer fake.unspentTokensIteratorByMutex.RUnlock()
	argsForCall := fake.unspentTokensIteratorByArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTokenFetcher) UnspentTokensIteratorByReturns(result1 sherdlock.Iterator[*token.UnspentTokenInWallet], result2 error) {
	fake.unspentTokensIteratorByMutex.Lock()
	defer fake.unspentTokensIteratorByMutex.Unlock()
	fake.UnspentTokensIteratorByStub = nil
	fake.unspentTokensIteratorByReturns = struct {
		result1 sherdlock.Iterator[*token.UnspentTokenInWallet]
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenFetcher) UnspentTokensIteratorByReturnsOnCall(i int, result1 sherdlock.Iterator[*token.UnspentTokenInWallet], result2 error) {
	fake.unspentTokensIteratorByMutex.Lock()
	defer fake.unspentTokensIteratorByMutex.Unlock()
	fake.UnspentTokensIteratorByStub = nil
	if fake.unspentTokensIteratorByReturnsOnCall == nil {
		fake.unspentTokensIteratorByReturnsOnCall = make(map[int]struct {
			result1 sherdlock.Iterator[*token.UnspentTokenInWallet]
			result2 error
		})
	}
	fake.unspentTokensIteratorByReturnsOnCall[i] = struct {
		result1 sherdlock.Iterator[*token.UnspentTokenInWallet]
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTokenFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sherdlock.TokenFetcher = new(FakeTokenFetcher)
