// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/LFDT-Panurus/panurus/token/services/selector/sherdlock"
	"github.com/LFDT-Panurus/panurus/token/token"
)

type FakeTokenFetcher struct {
	HasAnySpendableTokensStub        func(context.Context, string, token.Type) (bool, error)
	hasAnySpendableTokensMutex       sync.RWMutex
	hasAnySpendableTokensArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 token.Type
	}
	hasAnySpendableTokensReturns struct {
		result1 bool
		result2 error
	}
	hasAnySpendableTokensReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	UnspentTokensIteratorByStub        func(context.Context, string, token.Type) (sherdlock.Iterator[*token.UnspentTokenInWallet], error)
	unspentTokensIteratorByMutex       sync.RWMutex
	unspentTokensIteratorByArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 token.Type
	}
	unspentTokensIteratorByReturns struct {
		result1 sherdlock.Iterator[*token.UnspentTokenInWallet]
		result2 error
	}
	unspentTokensIteratorByReturnsOnCall map[int]struct {
		result1 sherdlock.Iterator[*token.UnspentTokenInWallet]
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTokenFetcher) HasAnySpendableTokens(arg1 context.Context, arg2 string, arg3 token.Type) (bool, error) {
	fake.hasAnySpendableTokensMutex.Lock()
	ret, specificReturn := fake.hasAnySpendableTokensReturnsOnCall[len(fake.hasAnySpendableTokensArgsForCall)]
	fake.hasAnySpendableTokensArgsForCall = append(fake.hasAnySpendableTokensArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 token.Type
	}{arg1, arg2, arg3})
	stub := fake.HasAnySpendableTokensStub
	fakeReturns := fake.hasAnySpendableTokensReturns
	fake.recordInvocation("HasAnySpendableTokens", []interface{}{arg1, arg2, arg3})
	fake.hasAnySpendableTokensMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTokenFetcher) HasAnySpendableTokensCallCount() int {
	fake.hasAnySpendableTokensMutex.RLock()
	defer fake.hasAnySpendableTokensMutex.RUnlock()
	return len(fake.hasAnySpendableTokensArgsForCall)
}

func (fake *FakeTokenFetcher) HasAnySpendableTokensCalls(stub func(context.Context, string, token.Type) (bool, error)) {
	fake.hasAnySpendableTokensMutex.Lock()
	defer fake.hasAnySpendableTokensMutex.Unlock()
	fake.HasAnySpendableTokensStub = stub
}

func (fake *FakeTokenFetcher) HasAnySpendableTokensArgsForCall(i int) (context.Context, string, token.Type) {
	fake.hasAnySpendableTokensMutex.RLock()
	defer fake.hasAnySpendableTokensMutex.RUnlock()
	argsForCall := fake.hasAnySpendableTokensArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTokenFetcher) HasAnySpendableTokensReturns(result1 bool, result2 error) {
	fake.hasAnySpendableTokensMutex.Lock()
	defer fake.hasAnySpendableTokensMutex.Unlock()
	fake.HasAnySpendableTokensStub = nil
	fake.hasAnySpendableTokensReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenFetcher) HasAnySpendableTokensReturnsOnCall(i int, result1 bool, result2 error) {
	fake.hasAnySpendableTokensMutex.Lock()
	defer fake.hasAnySpendableTokensMutex.Unlock()
	fake.HasAnySpendableTokensStub = nil
	if fake.hasAnySpendableTokensReturnsOnCall == nil {
		fake.hasAnySpendableTokensReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.hasAnySpendableTokensReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenFetcher) UnspentTokensIteratorBy(arg1 context.Context, arg2 string, arg3 token.Type) (sherdlock.Iterator[*token.UnspentTokenInWallet], error) {
	fake.unspentTokensIteratorByMutex.Lock()
	ret, specificReturn := fake.unspentTokensIteratorByReturnsOnCall[len(fake.unspentTokensIteratorByArgsForCall)]
	fake.unspentTokensIteratorByArgsForCall = append(fake.unspentTokensIteratorByArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 token.Type
	}{arg1, arg2, arg3})
	stub := fake.UnspentTokensIteratorByStub
	fakeReturns := fake.unspentTokensIteratorByReturns
	fake.recordInvocation("UnspentTokensIteratorBy", []interface{}{arg1, arg2, arg3})
	fake.unspentTokensIteratorByMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTokenFetcher) UnspentTokensIteratorByCallCount() int {
	fake.unspentTokensIteratorByMutex.RLock()
	defer fake.unspentTokensIteratorByMutex.RUnlock()
	return len(fake.unspentTokensIteratorByArgsForCall)
}

func (fake *FakeTokenFetcher) UnspentTokensIteratorByCalls(stub func(context.Context, string, token.Type) (sherdlock.Iterator[*token.UnspentTokenInWallet], error)) {
	fake.unspentTokensIteratorByMutex.Lock()
	defer fake.unspentTokensIteratorByMutex.Unlock()
	fake.UnspentTokensIteratorByStub = stub
}

func (fake *FakeTokenFetcher) UnspentTokensIteratorByArgsForCall(i int) (context.Context, string, token.Type) {
	fake.unspentTokensIteratorByMutex.RLock()
	defer fake.unspentTokensIteratorByMutex.RUnlock()
	argsForCall := fake.unspentTokensIteratorByArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTokenFetcher) UnspentTokensIteratorByReturns(result1 sherdlock.Iterator[*token.UnspentTokenInWallet], result2 error) {
	fake.unspentTokensIteratorByMutex.Lock()
	defer fake.unspentTokensIteratorByMutex.Unlock()
	fake.UnspentTokensIteratorByStub = nil
	fake.unspentTokensIteratorByReturns = struct {
		result1 sherdlock.Iterator[*token.UnspentTokenInWallet]
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenFetcher) UnspentTokensIteratorByReturnsOnCall(i int, result1 sherdlock.Iterator[*token.UnspentTokenInWallet], result2 error) {
	fake.unspentTokensIteratorByMutex.Lock()
	defer fake.unspentTokensIteratorByMutex.Unlock()
	fake.UnspentTokensIteratorByStub = nil
	if fake.unspentTokensIteratorByReturnsOnCall == nil {
		fake.unspentTokensIteratorByReturnsOnCall = make(map[int]struct {
			result1 sherdlock.Iterator[*token.UnspentTokenInWallet]
			result2 error
		})
	}
	fake.unspentTokensIteratorByReturnsOnCall[i] = struct {
		result1 sherdlock.Iterator[*token.UnspentTokenInWallet]
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTokenFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sherdlock.TokenFetcher = new(FakeTokenFetcher)
