/*
Copyright IBM Corp. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/

// Package setup provides circuit compilation, key generation, and
// serialization utilities for the zkatsnark driver's proof system.
//
// This package is used in two distinct contexts:
//   - Offline, once: SetupAll compiles all circuits and runs the trusted
//     setup ceremony (currently Groth16-only), populating a PublicParams
//     with proving and verification keys for distribution.
//   - Online, per-process startup: the prover and validator layers call
//     Compile*Circuit to reconstruct the constraint system (deterministic
//     and cheap, ~100ms) and LoadProvingKey/LoadVerifyingKey to deserialize
//     the keys already present in a distributed PublicParams. Neither of
//     these paths calls groth16.Setup, that only ever runs inside SetupAll.
package setup

import (
	"bytes"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark/backend/groth16"
	"github.com/consensys/gnark/constraint"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/r1cs"
	"github.com/hyperledger-labs/fabric-smart-client/pkg/utils/errors"

	"github.com/LFDT-Panurus/panurus/x/token/core/zkatsnark/circuit"
	"github.com/LFDT-Panurus/panurus/x/token/core/zkatsnark/pp"
)

// CircuitName identifies which circuit a proving/verification key or
// compiled constraint system belongs to. A named type instead of a bare
// string means an arbitrary, mistyped string can never be passed to
// LoadProvingKey/LoadVerifyingKey — only these three values compile.
type CircuitName string

const (
	CircuitSpend     CircuitName = "spend"
	CircuitOutput    CircuitName = "output"
	CircuitMigration CircuitName = "migration"
)

// ErrMissingKey is returned when a requested proving or verification key is
// absent from the given PublicParams i.e. setup.SetupAll has not yet been
// run, or was run without that particular circuit.
var ErrMissingKey = errors.New("setup: key missing from public parameters")

// ErrNotImplemented is returned for proof-system paths that are declared in
// PublicParams.ProofSystem but not yet implemented in this package.
var ErrNotImplemented = errors.New("setup: not yet implemented")

// ── Circuit compilation ────────────────────────────────────────────────────────
//
// These functions are deterministic given the same PublicParams field
// values that affect circuit shape (currently just Curve and, for
// OutputCircuit, MaxBits). Two calls with equivalent PublicParams always
// produce an equivalent constraint system. They are cheap (well under a
// second) and safe to call once per process at startup — there is no need
// to cache or serialize the constraint system itself.

// CompileSpendCircuit compiles circuit.SpendCircuit for the curve specified
// in p.Curve.
func CompileSpendCircuit(p *pp.PublicParams) (constraint.ConstraintSystem, error) {
	cs, err := frontend.Compile(
		p.Curve.ScalarField(),
		r1cs.NewBuilder,
		&circuit.SpendCircuit{},
	)
	if err != nil {
		return nil, errors.Wrapf(err, "setup: SpendCircuit compilation failed")
	}

	return cs, nil
}

// CompileOutputCircuit compiles circuit.OutputCircuit for the curve
// specified in p.Curve, with the range-check bit-width taken from p.MaxBits.
//
// MaxBits is a compile-time circuit parameter, not a witness value: two
// PublicParams differing only in MaxBits compile to two DIFFERENT circuits
// requiring separate keys. Always pass the same PublicParams (or one with
// an identical MaxBits) to CompileOutputCircuit as was used when the
// corresponding VKOutput/PKOutput were generated by SetupAll, otherwise
// proofs generated against one will not verify against the other.
func CompileOutputCircuit(p *pp.PublicParams) (constraint.ConstraintSystem, error) {
	if p.MaxBits <= 0 {
		return nil, errors.Errorf("setup: cannot compile OutputCircuit: MaxBits must be positive, got %d", p.MaxBits)
	}
	cs, err := frontend.Compile(
		p.Curve.ScalarField(),
		r1cs.NewBuilder,
		&circuit.OutputCircuit{MaxBits: p.MaxBits},
	)
	if err != nil {
		return nil, errors.Wrapf(err, "setup: OutputCircuit compilation failed")
	}

	return cs, nil
}

// ── Trusted setup ───────────────────────────────────────────────────────────────

// SetupAll compiles SpendCircuit and OutputCircuit and runs groth16.Setup
// for each, populating p.PKSpend/VKSpend and p.PKOutput/VKOutput in place.
// Call this once, offline. It is slow (the Groth16 setup ceremony itself
// takes seconds to tens of seconds per circuit depending on constraint
// count), do not call it on any request-serving path.
//
// The returned *pp.PublicParams is the same pointer passed in, mutated in
// place, returned for convenient chaining.
func SetupAll(p *pp.PublicParams) (*pp.PublicParams, error) {
	if p.ProofSystem != "groth16" {
		return nil, errors.Wrapf(ErrNotImplemented, "setup: SetupAll only supports groth16, got %q", p.ProofSystem)
	}

	// ── SpendCircuit ──────────────────────────────────────────────────────
	spendCS, err := CompileSpendCircuit(p)
	if err != nil {
		return nil, err
	}
	spendPK, spendVK, err := groth16.Setup(spendCS)
	if err != nil {
		return nil, errors.Wrapf(err, "setup: SpendCircuit groth16.Setup failed")
	}
	if p.PKSpend, err = SerializeProvingKey(spendPK); err != nil {
		return nil, errors.Wrapf(err, "setup: SpendCircuit proving key serialization")
	}
	if p.VKSpend, err = SerializeVerifyingKey(spendVK); err != nil {
		return nil, errors.Wrapf(err, "setup: SpendCircuit verifying key serialization")
	}

	// ── OutputCircuit ─────────────────────────────────────────────────────
	outputCS, err := CompileOutputCircuit(p)
	if err != nil {
		return nil, err
	}
	outputPK, outputVK, err := groth16.Setup(outputCS)
	if err != nil {
		return nil, errors.Wrapf(err, "setup: OutputCircuit groth16.Setup failed")
	}
	if p.PKOutput, err = SerializeProvingKey(outputPK); err != nil {
		return nil, errors.Wrapf(err, "setup: OutputCircuit proving key serialization")
	}
	if p.VKOutput, err = SerializeVerifyingKey(outputVK); err != nil {
		return nil, errors.Wrapf(err, "setup: OutputCircuit verifying key serialization")
	}

	if err := p.Validate(); err != nil {
		return nil, errors.Wrapf(err, "setup: resulting public params failed validation")
	}

	return p, nil
}

// ── Key serialization ─────────────────────────────────────────────────────────
//
// gnark's ProvingKey/VerifyingKey/Proof types all implement io.WriterTo /
// io.ReaderFrom, which these functions wrap directly. No custom encoding —
// this is exactly the format gnark itself reads and writes.

// SerializeProvingKey encodes a groth16.ProvingKey to bytes.
func SerializeProvingKey(pk groth16.ProvingKey) ([]byte, error) {
	var buf bytes.Buffer
	if _, err := pk.WriteTo(&buf); err != nil {
		return nil, errors.Wrapf(err, "setup: proving key serialize")
	}

	return buf.Bytes(), nil
}

// DeserializeProvingKey reconstructs a groth16.ProvingKey from bytes.
// curve must match the curve the key was generated for — passing the wrong
// curve produces either a decode error or, worse, a key that decodes
// without error but is silently wrong for that curve. Always source curve
// from the same PublicParams the key came from (p.Curve), never hardcode it.
func DeserializeProvingKey(raw []byte, curve ecc.ID) (groth16.ProvingKey, error) {
	pk := groth16.NewProvingKey(curve)
	if _, err := pk.ReadFrom(bytes.NewReader(raw)); err != nil {
		return nil, errors.Wrapf(err, "setup: proving key deserialize")
	}

	return pk, nil
}

// SerializeVerifyingKey encodes a groth16.VerifyingKey to bytes.
func SerializeVerifyingKey(vk groth16.VerifyingKey) ([]byte, error) {
	var buf bytes.Buffer
	if _, err := vk.WriteTo(&buf); err != nil {
		return nil, errors.Wrapf(err, "setup: verifying key serialize")
	}

	return buf.Bytes(), nil
}

// DeserializeVerifyingKey reconstructs a groth16.VerifyingKey from bytes.
// Same curve-matching caveat as DeserializeProvingKey applies.
func DeserializeVerifyingKey(raw []byte, curve ecc.ID) (groth16.VerifyingKey, error) {
	vk := groth16.NewVerifyingKey(curve)
	if _, err := vk.ReadFrom(bytes.NewReader(raw)); err != nil {
		return nil, errors.Wrapf(err, "setup: verifying key deserialize")
	}

	return vk, nil
}

// ── Key loading by circuit type ───────────────────────────────────────────────
//
// These are the functions the prover and validator layers actually call at
// startup: given a fully-populated PublicParams (post-SetupAll, or received
// over the network already populated), load the concrete key for a named
// circuit.

// LoadProvingKey retrieves and deserializes the proving key for the named
// circuit (CircuitSpend, CircuitOutput, or CircuitMigration) from p.
func LoadProvingKey(p *pp.PublicParams, circuitName CircuitName) (groth16.ProvingKey, error) {
	var raw []byte
	switch circuitName {
	case CircuitSpend:
		raw = p.PKSpend
	case CircuitOutput:
		raw = p.PKOutput
	case CircuitMigration:
		raw = p.PKMigration
	default:
		return nil, errors.Errorf("setup: unknown circuit name %q", circuitName)
	}
	if len(raw) == 0 {
		return nil, errors.Wrapf(ErrMissingKey, "no proving key for circuit %q", circuitName)
	}

	return DeserializeProvingKey(raw, p.Curve)
}

// LoadVerifyingKey retrieves and deserializes the verification key for the
// named circuit (CircuitSpend, CircuitOutput, or CircuitMigration) from p.
func LoadVerifyingKey(p *pp.PublicParams, circuitName CircuitName) (groth16.VerifyingKey, error) {
	var raw []byte
	switch circuitName {
	case CircuitSpend:
		raw = p.VKSpend
	case CircuitOutput:
		raw = p.VKOutput
	case CircuitMigration:
		raw = p.VKMigration
	default:
		return nil, errors.Errorf("setup: unknown circuit name %q", circuitName)
	}
	if len(raw) == 0 {
		return nil, errors.Wrapf(ErrMissingKey, "no verifying key for circuit %q", circuitName)
	}

	return DeserializeVerifyingKey(raw, p.Curve)
}

// ── Proof serialization ────────────────────────────────────────────────────────
//
// Groth16 proofs are a fixed 192 bytes for BLS12-381 regardless of circuit
// complexity, used by the Orchestrator (prover layer) to produce the wire
// format's SpendProof/OutputProof byte slices, and will be used by the
// validator layer to reconstruct a groth16.Proof before calling
// groth16.Verify.

// SerializeProof encodes a groth16.Proof to bytes.
func SerializeProof(proof groth16.Proof) ([]byte, error) {
	var buf bytes.Buffer
	if _, err := proof.WriteTo(&buf); err != nil {
		return nil, errors.Wrapf(err, "setup: proof serialize")
	}

	return buf.Bytes(), nil
}

// DeserializeProof reconstructs a groth16.Proof from bytes. curve must
// match the curve the proof was generated for.
func DeserializeProof(raw []byte, curve ecc.ID) (groth16.Proof, error) {
	proof := groth16.NewProof(curve)
	if _, err := proof.ReadFrom(bytes.NewReader(raw)); err != nil {
		return nil, errors.Wrapf(err, "setup: proof deserialize")
	}

	return proof, nil
}
