// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/LFDT-Panurus/panurus/token/services/network/fabricx/pp"
	"github.com/hyperledger-labs/fabric-smart-client/platform/common/driver"
)

type SetupVersionReader struct {
	FetchSetupHashVersionStub        func(driver.Network, driver.Channel, driver.Namespace) (uint64, bool, error)
	fetchSetupHashVersionMutex       sync.RWMutex
	fetchSetupHashVersionArgsForCall []struct {
		arg1 driver.Network
		arg2 driver.Channel
		arg3 driver.Namespace
	}
	fetchSetupHashVersionReturns struct {
		result1 uint64
		result2 bool
		result3 error
	}
	fetchSetupHashVersionReturnsOnCall map[int]struct {
		result1 uint64
		result2 bool
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *SetupVersionReader) FetchSetupHashVersion(arg1 driver.Network, arg2 driver.Channel, arg3 driver.Namespace) (uint64, bool, error) {
	fake.fetchSetupHashVersionMutex.Lock()
	ret, specificReturn := fake.fetchSetupHashVersionReturnsOnCall[len(fake.fetchSetupHashVersionArgsForCall)]
	fake.fetchSetupHashVersionArgsForCall = append(fake.fetchSetupHashVersionArgsForCall, struct {
		arg1 driver.Network
		arg2 driver.Channel
		arg3 driver.Namespace
	}{arg1, arg2, arg3})
	stub := fake.FetchSetupHashVersionStub
	fakeReturns := fake.fetchSetupHashVersionReturns
	fake.recordInvocation("FetchSetupHashVersion", []interface{}{arg1, arg2, arg3})
	fake.fetchSetupHashVersionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *SetupVersionReader) FetchSetupHashVersionCallCount() int {
	fake.fetchSetupHashVersionMutex.RLock()
	defer fake.fetchSetupHashVersionMutex.RUnlock()
	return len(fake.fetchSetupHashVersionArgsForCall)
}

func (fake *SetupVersionReader) FetchSetupHashVersionCalls(stub func(driver.Network, driver.Channel, driver.Namespace) (uint64, bool, error)) {
	fake.fetchSetupHashVersionMutex.Lock()
	defer fake.fetchSetupHashVersionMutex.Unlock()
	fake.FetchSetupHashVersionStub = stub
}

func (fake *SetupVersionReader) FetchSetupHashVersionArgsForCall(i int) (driver.Network, driver.Channel, driver.Namespace) {
	fake.fetchSetupHashVersionMutex.RLock()
	defer fake.fetchSetupHashVersionMutex.RUnlock()
	argsForCall := fake.fetchSetupHashVersionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *SetupVersionReader) FetchSetupHashVersionReturns(result1 uint64, result2 bool, result3 error) {
	fake.fetchSetupHashVersionMutex.Lock()
	defer fake.fetchSetupHashVersionMutex.Unlock()
	fake.FetchSetupHashVersionStub = nil
	fake.fetchSetupHashVersionReturns = struct {
		result1 uint64
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *SetupVersionReader) FetchSetupHashVersionReturnsOnCall(i int, result1 uint64, result2 bool, result3 error) {
	fake.fetchSetupHashVersionMutex.Lock()
	defer fake.fetchSetupHashVersionMutex.Unlock()
	fake.FetchSetupHashVersionStub = nil
	if fake.fetchSetupHashVersionReturnsOnCall == nil {
		fake.fetchSetupHashVersionReturnsOnCall = make(map[int]struct {
			result1 uint64
			result2 bool
			result3 error
		})
	}
	fake.fetchSetupHashVersionReturnsOnCall[i] = struct {
		result1 uint64
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *SetupVersionReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *SetupVersionReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pp.SetupVersionReader = new(SetupVersionReader)
