"""Regenerate the static `www/` dashboard from the SQLite database.

Fully static, self-contained HTML (no CDN, no JS runtime) -- see
docs/development/perflab.md. Charts are inline SVG from `svg_chart.py`.
Called after every ingest (`cli.py work`) and on a 15-minute timer
(`perflab-report.timer`), and is idempotent/re-entrant: it only reads the DB
and always rewrites the same set of files.
"""

from __future__ import annotations

import csv
import html
import sqlite3
import statistics
from pathlib import Path

import jinja2

from .paths import Layout
from .svg_chart import Point, line_chart, sparkline

_ENV = jinja2.Environment(autoescape=True, trim_blocks=True, lstrip_blocks=True)

_BASE_CSS = """
:root {
  --surface: #fcfcfb; --ink: #0b0b0b; --ink-2: #52514e; --ink-muted: #898781;
  --gridline: #e1e0d9; --accent: #2a78d6;
  --good: #0ca30c; --warning: #fab219; --serious: #ec835a; --critical: #d03b3b;
}
* { box-sizing: border-box; }
body { font-family: system-ui, -apple-system, "Segoe UI", sans-serif; margin: 0;
       background: var(--surface); color: var(--ink); }
header { padding: 16px 24px; border-bottom: 1px solid var(--gridline); }
header a { color: var(--ink); text-decoration: none; font-weight: 600; margin-right: 20px; }
header a:hover { color: var(--accent); }
main { padding: 24px; max-width: 1100px; margin: 0 auto; }
h1 { font-size: 1.4rem; } h2 { font-size: 1.1rem; color: var(--ink-2); }
table { width: 100%; border-collapse: collapse; margin: 12px 0 32px; }
th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid var(--gridline); font-size: 0.9rem; }
th { color: var(--ink-muted); font-weight: 600; font-size: 0.8rem; text-transform: uppercase; }
.badge { display: inline-flex; align-items: center; gap: 4px; padding: 2px 8px; border-radius: 10px;
         font-size: 0.78rem; font-weight: 600; }
.badge-regressed { background: color-mix(in srgb, var(--critical) 15%, white); color: var(--critical); }
.badge-suspected { background: color-mix(in srgb, var(--warning) 18%, white); color: #8a5a00; }
.badge-improved { background: color-mix(in srgb, var(--good) 15%, white); color: var(--good); }
.badge-neutral { background: var(--gridline); color: var(--ink-2); }
.badge-harness-changed, .badge-noisy { background: var(--gridline); color: var(--ink-muted); }
.mono { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.85rem; }
.muted { color: var(--ink-muted); }
a.bench-link { color: var(--accent); text-decoration: none; }
a.bench-link:hover { text-decoration: underline; }
footer { padding: 24px; color: var(--ink-muted); font-size: 0.8rem; text-align: center; }
"""

_STATUS_LABEL = {
    "regressed": "\U0001F534 regressed", "suspected": "\U0001F7E1 suspected",
    "improved": "\U0001F7E2 improved", "neutral": "➖ neutral",
    "harness-changed": "❓ harness changed", "new": "ℹ️ new",
    "removed": "ℹ️ removed",
}

_NAV = (
    '<header><a href="index.html">Overview</a><a href="prs.html">Pull Requests</a>'
    '<a href="runs.html">Runs</a><a href="health.html">Host health</a></header>'
)

_PAGE = _ENV.from_string("""<!doctype html><html lang="en"><head>
<meta charset="utf-8"><title>PerfLab - {{ title }}</title>
<style>{{ css|safe }}</style></head><body>{{ nav|safe }}
<main>{{ body|safe }}</main>
<footer>PerfLab &middot; generated by cmd/benchmarking/perflab/report.py</footer>
</body></html>
""")


def _write(layout: Layout, rel_path: str, title: str, body: str) -> None:
    out = layout.www / rel_path
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_PAGE.render(title=title, css=_BASE_CSS, nav=_NAV, body=body))


def _badge(status: str) -> str:
    label = _STATUS_LABEL.get(status, status)
    return f'<span class="badge badge-{html.escape(status)}">{html.escape(label)}</span>'


def _bench_names(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        "SELECT DISTINCT bench FROM measurements WHERE bench NOT LIKE '%-canary-%' ORDER BY bench"
    ).fetchall()
    return [r["bench"] for r in rows]


def _main_series(conn: sqlite3.Connection, bench: str, metric: str = "ns/op",
                  limit: int = 60) -> list[tuple[str, str, float, str]]:
    """[(run_id, commit_short, median_value, verdict_status)] oldest-first, for
    the last `limit` non-noisy solo `main` runs of one series."""
    rows = conn.execute(
        "SELECT r.run_id, r.commit_sha, r.started_at, "
        "GROUP_CONCAT(m.value) AS vals FROM measurements m "
        "JOIN runs r ON r.run_id = m.run_id "
        "WHERE r.kind='main' AND r.noisy=0 AND m.side='solo' AND m.bench=? AND m.metric=? "
        "GROUP BY r.run_id ORDER BY r.started_at DESC LIMIT ?",
        (bench, metric, limit),
    ).fetchall()
    out = []
    for r in reversed(rows):
        values = [float(v) for v in r["vals"].split(",")]
        vrow = conn.execute(
            "SELECT status FROM verdicts WHERE run_id=? AND bench=? AND metric=? LIMIT 1",
            (r["run_id"], bench, metric),
        ).fetchone()
        status = vrow["status"] if vrow else "neutral"
        out.append((r["run_id"], r["commit_sha"][:9], statistics.median(values), status))
    return out


def _index_body(conn: sqlite3.Connection) -> str:
    rows_html = []
    entries = []
    for bench in _bench_names(conn):
        series = _main_series(conn, bench, limit=30)
        if not series:
            continue
        latest_status = series[-1][3]
        latest_value = series[-1][2]
        oldest_value = series[0][2]
        pct = 0.0 if oldest_value == 0 else (latest_value - oldest_value) / oldest_value * 100.0
        entries.append((bench, series, latest_status, latest_value, pct))
    # worst-delta first: slowdowns (positive pct) sorted to the top.
    entries.sort(key=lambda e: -e[4])
    for bench, series, status, latest_value, pct in entries:
        spark = sparkline([v for _, _, v, _ in series], status=status)
        rows_html.append(
            f'<tr><td><a class="bench-link" href="bench/{html.escape(bench)}.html">'
            f'{html.escape(bench)}</a></td>'
            f'<td class="mono">{latest_value:,.0f} ns/op</td>'
            f'<td class="mono">{pct:+.1f}%</td><td>{spark}</td><td>{_badge(status)}</td></tr>'
        )
    table = (
        '<table><thead><tr><th>Benchmark</th><th>Latest</th><th>&Delta; over window</th>'
        f'<th>Trend</th><th>Status</th></tr></thead><tbody>{"".join(rows_html)}</tbody></table>'
        if rows_html else '<p class="muted">No Tier-1 data ingested yet.</p>'
    )
    return f"<h1>Tier-1 benchmark overview</h1>{table}"


def _bench_body(conn: sqlite3.Connection, bench: str) -> str:
    sections = []
    for metric in ("ns/op", "B/op", "allocs/op"):
        series = _main_series(conn, bench, metric=metric, limit=120)
        if not series:
            continue
        points = [Point(x_label=short, value=v, status=st) for _, short, v, st in series]
        svg = line_chart(points, unit=metric, title=f"{bench} {metric}")
        sections.append(f"<h2>{html.escape(metric)}</h2>{svg}")
    body = f"<h1>{html.escape(bench)}</h1>"
    body += "".join(sections) if sections else '<p class="muted">No history yet.</p>'
    return body


def _prs_body(conn: sqlite3.Connection) -> str:
    rows = conn.execute(
        "SELECT run_id, pr_number, commit_sha, baseline_sha, started_at, noisy "
        "FROM runs WHERE kind IN ('pr','confirm') ORDER BY started_at DESC LIMIT 100"
    ).fetchall()
    out = ['<h1>Pull requests &amp; confirmations</h1>',
           '<table><thead><tr><th>PR</th><th>Head</th><th>Base</th><th>Started</th>'
           '<th>Noisy</th><th>Summary</th></tr></thead><tbody>']
    for r in rows:
        pr = f"#{r['pr_number']}" if r["pr_number"] else "(confirm)"
        out.append(
            f"<tr><td>{pr}</td><td class=\"mono\">{r['commit_sha'][:9]}</td>"
            f"<td class=\"mono\">{(r['baseline_sha'] or '')[:9]}</td>"
            f"<td>{html.escape(r['started_at'] or '')}</td>"
            f"<td>{'yes' if r['noisy'] else 'no'}</td>"
            f"<td><a class=\"bench-link\" href=\"../runs/{r['run_id']}/summary.md\">summary.md</a></td></tr>"
        )
    out.append("</tbody></table>")
    return "".join(out)


def _runs_body(conn: sqlite3.Connection) -> str:
    rows = conn.execute(
        "SELECT run_id, kind, commit_sha, started_at, status, noisy FROM runs "
        "ORDER BY started_at DESC LIMIT 300"
    ).fetchall()
    out = ['<h1>Run index</h1>',
           '<table><thead><tr><th>Run</th><th>Kind</th><th>Commit</th><th>Started</th>'
           '<th>Status</th></tr></thead><tbody>']
    for r in rows:
        flag = " (noisy)" if r["noisy"] else ""
        out.append(
            f"<tr><td class=\"mono\">{html.escape(r['run_id'])}</td><td>{html.escape(r['kind'])}</td>"
            f"<td class=\"mono\">{r['commit_sha'][:9]}</td><td>{html.escape(r['started_at'] or '')}</td>"
            f"<td>{html.escape(r['status'])}{flag}</td></tr>"
        )
    out.append("</tbody></table>")
    return "".join(out)


def write_health(layout: Layout, checks: dict[str, str], ok: bool) -> None:
    rows = "".join(f"<tr><td>{html.escape(k)}</td><td class=\"mono\">{html.escape(str(v))}</td></tr>"
                    for k, v in checks.items())
    body = (f"<h1>Host health {'✅' if ok else '❌'}</h1>"
            f"<table><tbody>{rows}</tbody></table>")
    _write(layout, "health.html", "Host health", body)


def _export_csv(layout: Layout, conn: sqlite3.Connection) -> None:
    layout.export.mkdir(parents=True, exist_ok=True)
    rows = conn.execute(
        "SELECT m.run_id, r.kind, r.commit_sha, r.started_at, m.side, m.bench, "
        "m.params_json, m.workers, m.metric, m.sample_idx, m.value FROM measurements m "
        "JOIN runs r ON r.run_id = m.run_id ORDER BY r.started_at"
    ).fetchall()
    out_path = layout.export / "measurements.csv"
    with out_path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["run_id", "kind", "commit_sha", "started_at", "side", "bench",
                          "params_json", "workers", "metric", "sample_idx", "value"])
        for r in rows:
            writer.writerow(list(r))


def generate(layout: Layout, conn: sqlite3.Connection) -> None:
    _write(layout, "index.html", "Overview", _index_body(conn))
    _write(layout, "prs.html", "Pull Requests", _prs_body(conn))
    _write(layout, "runs.html", "Runs", _runs_body(conn))
    for bench in _bench_names(conn):
        _write(layout, f"bench/{bench}.html", bench, _bench_body(conn, bench))
    if not (layout.www / "health.html").exists():
        write_health(layout, {"status": "perflab doctor has not run yet"}, ok=False)
    _export_csv(layout, conn)
