// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/LFDT-Panurus/panurus/token/driver"
	"github.com/LFDT-Panurus/panurus/token/services/identity"
)

type ConfIDResolver struct {
	GetConfIDStub        func(context.Context, driver.Identity) (string, error)
	getConfIDMutex       sync.RWMutex
	getConfIDArgsForCall []struct {
		arg1 context.Context
		arg2 driver.Identity
	}
	getConfIDReturns struct {
		result1 string
		result2 error
	}
	getConfIDReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ConfIDResolver) GetConfID(arg1 context.Context, arg2 driver.Identity) (string, error) {
	fake.getConfIDMutex.Lock()
	ret, specificReturn := fake.getConfIDReturnsOnCall[len(fake.getConfIDArgsForCall)]
	fake.getConfIDArgsForCall = append(fake.getConfIDArgsForCall, struct {
		arg1 context.Context
		arg2 driver.Identity
	}{arg1, arg2})
	stub := fake.GetConfIDStub
	fakeReturns := fake.getConfIDReturns
	fake.recordInvocation("GetConfID", []interface{}{arg1, arg2})
	fake.getConfIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ConfIDResolver) GetConfIDCallCount() int {
	fake.getConfIDMutex.RLock()
	defer fake.getConfIDMutex.RUnlock()
	return len(fake.getConfIDArgsForCall)
}

func (fake *ConfIDResolver) GetConfIDCalls(stub func(context.Context, driver.Identity) (string, error)) {
	fake.getConfIDMutex.Lock()
	defer fake.getConfIDMutex.Unlock()
	fake.GetConfIDStub = stub
}

func (fake *ConfIDResolver) GetConfIDArgsForCall(i int) (context.Context, driver.Identity) {
	fake.getConfIDMutex.RLock()
	defer fake.getConfIDMutex.RUnlock()
	argsForCall := fake.getConfIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ConfIDResolver) GetConfIDReturns(result1 string, result2 error) {
	fake.getConfIDMutex.Lock()
	defer fake.getConfIDMutex.Unlock()
	fake.GetConfIDStub = nil
	fake.getConfIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ConfIDResolver) GetConfIDReturnsOnCall(i int, result1 string, result2 error) {
	fake.getConfIDMutex.Lock()
	defer fake.getConfIDMutex.Unlock()
	fake.GetConfIDStub = nil
	if fake.getConfIDReturnsOnCall == nil {
		fake.getConfIDReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getConfIDReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ConfIDResolver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ConfIDResolver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ identity.ConfIDResolver = new(ConfIDResolver)
