/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package pp

import (
	"github.com/LFDT-Panurus/panurus/token"
	"github.com/LFDT-Panurus/panurus/token/services/logging"
	"github.com/LFDT-Panurus/panurus/token/services/network/common/rws/keys"
	"github.com/hyperledger-labs/fabric-smart-client/pkg/utils/errors"
	"github.com/hyperledger-labs/fabric-smart-client/platform/common/driver"
	"github.com/hyperledger-labs/fabric-smart-client/platform/fabricx/core/committer/queryservice"
	"google.golang.org/protobuf/encoding/protowire"
)

var logger = logging.MustGetLogger()

// PublicParametersService models a service for fetching and loading public parameters.
type PublicParametersService struct {
	tmsProvider *token.ManagementServiceProvider
	qsProvider  queryservice.Provider
	translator  *keys.Translator
}

// NewPublicParametersService returns a new PublicParametersService instance
// for fetching and loading public parameters using a query service provider
// and a TMS provider.
func NewPublicParametersService(tmsProvider *token.ManagementServiceProvider, qsProvider queryservice.Provider) *PublicParametersService {
	return &PublicParametersService{
		tmsProvider: tmsProvider,
		qsProvider:  qsProvider,
		translator:  &keys.Translator{},
	}
}

// LoadPublicParams updates the public parameters for the given TMS ID
// in the token management service provider.
func (f *PublicParametersService) LoadPublicParams(tmsID token.TMSID, ppRaw []byte) error {
	return f.tmsProvider.Update(tmsID, ppRaw)
}

// Fetch retrieves the raw public parameters from the ledger for the specified
// network, channel, and namespace. It uses the setup key generated by
// the translator to query the state.
func (f *PublicParametersService) Fetch(network driver.Network, channel driver.Channel, namespace driver.Namespace) ([]byte, error) {
	qs, err := f.qsProvider.Get(network, channel)
	if err != nil {
		return nil, errors.Wrapf(err, "failed getting query service")
	}
	k, err := f.translator.CreateSetupKey()
	if err != nil {
		return nil, errors.Wrapf(err, "failed creating setup key")
	}
	value, err := qs.GetState(namespace, k)
	if err != nil {
		return nil, errors.Wrapf(err, "failed getting state")
	}
	if value == nil {
		return nil, nil
	}

	return value.Raw, nil
}

// FetchNamespaceVersion retrieves the current namespace policy version from the
// ledger using qs.GetState("_meta", namespace). This is the same key and encoding
// used by the fabricx vault marshaller (platform/fabricx/core/vault/marshal.go) to
// derive NsVersion for ordinary token transactions — a single source of truth.
//
// Returns an error when the namespace has no "_meta" entry so a misconfigured or
// unregistered namespace is surfaced at deploy time rather than silently submitting
// a NsVersion: 0 transaction that the committer will reject.
func (f *PublicParametersService) FetchNamespaceVersion(network driver.Network, channel driver.Channel, namespace driver.Namespace) (uint64, error) {
	qs, err := f.qsProvider.Get(network, channel)
	if err != nil {
		return 0, errors.Wrapf(err, "failed getting query service for [%s/%s]", network, channel)
	}

	value, err := qs.GetState("_meta", namespace)
	if err != nil {
		return 0, errors.Wrapf(err, "failed reading _meta version for namespace [%s]", namespace)
	}
	if value == nil {
		return 0, errors.Errorf("namespace [%s] has no _meta entry on [%s/%s] — namespace not registered on this channel", namespace, network, channel)
	}

	// Version bytes are encoded as a protobuf varint — same as UnmarshalVersion in
	// platform/fabricx/core/vault/marshal.go.
	version, _ := protowire.ConsumeVarint(value.Version)

	return version, nil
}

// Loader models a loader for public parameters.
type Loader interface {
	// LoadPublicParams loads the public parameters for the given TMS ID.
	LoadPublicParams(TMSID token.TMSID, ppRaw []byte) error
}
