/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package pp

import (
	"github.com/LFDT-Panurus/panurus/token"
	"github.com/LFDT-Panurus/panurus/token/services/logging"
	"github.com/LFDT-Panurus/panurus/token/services/network/common/rws/keys"
	"github.com/hyperledger-labs/fabric-smart-client/pkg/utils/errors"
	"github.com/hyperledger-labs/fabric-smart-client/platform/common/driver"
	"github.com/hyperledger-labs/fabric-smart-client/platform/fabricx/core/committer/queryservice"
	"github.com/hyperledger-labs/fabric-smart-client/platform/fabricx/core/vault"
	"google.golang.org/protobuf/encoding/protowire"
)

var logger = logging.MustGetLogger()

// QueryService models the FabricX query service needed to read public parameters.
//
//go:generate counterfeiter -o mock/qs.go -fake-name QueryService . QueryService
type QueryService = queryservice.QueryService

// QueryServiceProvider is an alias for queryservice.Provider.
//
//go:generate counterfeiter -o mock/qps.go -fake-name QueryServiceProvider . QueryServiceProvider
type QueryServiceProvider = queryservice.Provider

// PublicParametersService models a service for fetching and loading public parameters.
type PublicParametersService struct {
	tmsProvider *token.ManagementServiceProvider
	qsProvider  queryservice.Provider
	translator  *keys.Translator
}

// NewPublicParametersService returns a new PublicParametersService instance
// for fetching and loading public parameters using a query service provider
// and a TMS provider.
func NewPublicParametersService(tmsProvider *token.ManagementServiceProvider, qsProvider queryservice.Provider) *PublicParametersService {
	return &PublicParametersService{
		tmsProvider: tmsProvider,
		qsProvider:  qsProvider,
		translator:  &keys.Translator{},
	}
}

// LoadPublicParams updates the public parameters for the given TMS ID
// in the token management service provider.
func (f *PublicParametersService) LoadPublicParams(tmsID token.TMSID, ppRaw []byte) error {
	return f.tmsProvider.Update(tmsID, ppRaw)
}

// Fetch retrieves the raw public parameters from the ledger for the specified
// network, channel, and namespace. It uses the setup key generated by
// the translator to query the state.
func (f *PublicParametersService) Fetch(network driver.Network, channel driver.Channel, namespace driver.Namespace) ([]byte, error) {
	qs, err := f.qsProvider.Get(network, channel)
	if err != nil {
		return nil, errors.Wrapf(err, "failed getting query service")
	}
	k, err := f.translator.CreateSetupKey()
	if err != nil {
		return nil, errors.Wrapf(err, "failed creating setup key")
	}
	value, err := qs.GetState(namespace, k)
	if err != nil {
		return nil, errors.Wrapf(err, "failed getting state")
	}
	if value == nil {
		return nil, nil
	}

	return value.Raw, nil
}

// FetchSetupHashVersion retrieves the ledger version of the public parameters
// setup hash key for the specified network, channel, and namespace. This is the
// key for which every token transaction carries a versioned read dependency, so
// its row version is the version an endorser must attach to the transactions it
// translates.
// The returned boolean reports whether the key exists on the ledger at all; when
// it does not, the returned version is zero.
func (f *PublicParametersService) FetchSetupHashVersion(network driver.Network, channel driver.Channel, namespace driver.Namespace) (uint64, bool, error) {
	qs, err := f.qsProvider.Get(network, channel)
	if err != nil {
		return 0, false, errors.Wrapf(err, "failed getting query service")
	}
	k, err := f.translator.CreateSetupHashKey()
	if err != nil {
		return 0, false, errors.Wrapf(err, "failed creating setup hash key")
	}
	value, err := qs.GetState(namespace, k)
	if err != nil {
		return 0, false, errors.Wrapf(err, "failed getting state")
	}
	if value == nil {
		return 0, false, nil
	}

	return vault.UnmarshalVersion(value.Version), true, nil
}

// FetchNamespaceVersion retrieves the current namespace policy version from the
// ledger using qs.GetState("_meta", namespace). This is the same key and varint
// encoding used by the fabricx vault marshaller (platform/fabricx/core/vault/marshal.go)
// to derive NsVersion for ordinary token transactions — establishing a single source of truth.
//
// If the namespace has no "_meta" entry on the ledger or has an empty version (e.g. for an
// initial deployment), it logs at Debug level and returns initial version 0.
// If the version bytes cannot be decoded as a varint (negative length from protowire.ConsumeVarint),
// it surfaces an error rather than silently defaulting to 0.
func (f *PublicParametersService) FetchNamespaceVersion(network driver.Network, channel driver.Channel, namespace driver.Namespace) (uint64, error) {
	qs, err := f.qsProvider.Get(network, channel)
	if err != nil {
		return 0, errors.Wrapf(err, "failed getting query service for [%s/%s]", network, channel)
	}

	value, err := qs.GetState("_meta", namespace)
	if err != nil {
		return 0, errors.Wrapf(err, "failed reading _meta version for namespace [%s]", namespace)
	}
	if value == nil || len(value.Version) == 0 {
		logger.Debugf("namespace [%s] has no _meta entry or empty version on [%s/%s] — returning initial version 0", namespace, network, channel)

		return 0, nil
	}

	// Version bytes are encoded as a protobuf varint — same as UnmarshalVersion in
	// platform/fabricx/core/vault/marshal.go.
	version, n := protowire.ConsumeVarint(value.Version)
	if n < 0 {
		return 0, errors.Errorf("failed decoding _meta version for namespace [%s]: invalid varint", namespace)
	}

	return version, nil
}

// Loader models a loader for public parameters.
type Loader interface {
	// LoadPublicParams loads the public parameters for the given TMS ID.
	LoadPublicParams(TMSID token.TMSID, ppRaw []byte) error
}
