name: Check Markdown links

on:
  push:
    branches: [ main, feature/evm-network-driver, feature/zkat-snark-driver ]
  pull_request:
    branches: [ main, feature/evm-network-driver, feature/zkat-snark-driver ]

permissions:
  contents: read
  pull-requests: write

jobs:
  check-links:
    name: runner / linkspector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@568ec8d29fa92b31fd9ea5381e155c51e922af83 # v1.5.5
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true